production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV["POSTGRESQL_PORT_5432_TCP_ADDR"] %>
  port: <%= ENV["POSTGRESQL_PORT_5432_TCP_PORT"] %>
  database: <%= ENV["POSTGRESQL_INSTANCE_NAME"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>